// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurboSquadApp.Data;

#nullable disable

namespace TurboSquadApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926182103_RenameToSnakeCase")]
    partial class RenameToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TurboSquadApp.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrigadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("brigade_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("BrigadeId")
                        .HasDatabaseName("ix_users_brigade_id");

                    b.HasIndex("DepotId")
                        .HasDatabaseName("ix_users_depot_id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("UserId", "Role")
                        .HasName("pk_user_roles");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.Brigade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_brigades");

                    b.HasIndex("DepotId")
                        .HasDatabaseName("ix_brigades_depot_id");

                    b.ToTable("brigades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Бригада 1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Бригада 2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Бригада 3"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Бригада 1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Бригада 2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Бригада 3"
                        });
                });

            modelBuilder.Entity("TurboSquadApp.Data.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_depots");

                    b.ToTable("depots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Северное депо"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Южное депо"
                        });
                });

            modelBuilder.Entity("TurboSquadApp.Data.AppUser", b =>
                {
                    b.HasOne("TurboSquadApp.Data.Brigade", "Brigade")
                        .WithMany()
                        .HasForeignKey("BrigadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_brigades_brigade_id");

                    b.HasOne("TurboSquadApp.Data.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_depots_depot_id");

                    b.Navigation("Brigade");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("TurboSquadApp.Data.AppUserRole", b =>
                {
                    b.HasOne("TurboSquadApp.Data.AppUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurboSquadApp.Data.Brigade", b =>
                {
                    b.HasOne("TurboSquadApp.Data.Depot", "Depot")
                        .WithMany("Brigades")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brigades_depots_depot_id");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("TurboSquadApp.Data.AppUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TurboSquadApp.Data.Depot", b =>
                {
                    b.Navigation("Brigades");
                });
#pragma warning restore 612, 618
        }
    }
}
