// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurboSquadApp.Data;

#nullable disable

namespace TurboSquadApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927171701_AddBlitzSessions")]
    partial class AddBlitzSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TurboSquadApp.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrigadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("brigade_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("BrigadeId")
                        .HasDatabaseName("ix_users_brigade_id");

                    b.HasIndex("DepotId")
                        .HasDatabaseName("ix_users_depot_id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("UserId", "Role")
                        .HasName("pk_user_roles");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.BlitzAnswerRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_ms");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_id");

                    b.Property<string>("SelectedOptionIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_option_ids");

                    b.Property<bool>("TimedOut")
                        .HasColumnType("boolean")
                        .HasColumnName("timed_out");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verdict");

                    b.HasKey("SessionId", "Seq")
                        .HasName("pk_blitz_answers");

                    b.HasIndex("SessionId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_blitz_answers_session_id_question_id");

                    b.ToTable("blitz_answers", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.BlitzSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Deck")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("deck");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset?>("QuestionShownAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("question_shown_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_blitz_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_blitz_sessions_user_id");

                    b.ToTable("blitz_sessions", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.Brigade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid")
                        .HasColumnName("depot_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_brigades");

                    b.HasIndex("DepotId")
                        .HasDatabaseName("ix_brigades_depot_id");

                    b.ToTable("brigades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Бригада 1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Бригада 2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Бригада 3"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Бригада 1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Бригада 2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            DepotId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Бригада 3"
                        });
                });

            modelBuilder.Entity("TurboSquadApp.Data.ConductorProfileRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("RankIndex")
                        .HasColumnType("integer")
                        .HasColumnName("rank_index");

                    b.HasKey("UserId")
                        .HasName("pk_conductor_profiles");

                    b.ToTable("conductor_profiles", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_depots");

                    b.ToTable("depots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Северное депо"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Южное депо"
                        });
                });

            modelBuilder.Entity("TurboSquadApp.Data.EventDocumentRecord", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("EventId", "Version")
                        .HasName("pk_event_documents");

                    b.ToTable("event_documents", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.EventDraftRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_event_drafts");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_event_drafts_source_id");

                    b.ToTable("event_drafts", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.KnowledgeMasteryRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UnitType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_type");

                    b.Property<string>("UnitId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("unit_id");

                    b.Property<string>("Competence")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("competence");

                    b.Property<int>("AwardedCost")
                        .HasColumnType("integer")
                        .HasColumnName("awarded_cost");

                    b.Property<bool>("IsMastered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mastered");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.HasKey("UserId", "UnitType", "UnitId", "Competence")
                        .HasName("pk_knowledge_masteries");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_knowledge_masteries_user_id");

                    b.ToTable("knowledge_masteries", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.QuestionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<double>("BaseFrequency")
                        .HasColumnType("double precision")
                        .HasColumnName("base_frequency");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("categories");

                    b.Property<string>("ExplanationKeyFact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation_key_fact");

                    b.Property<string>("ExplanationText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation_text");

                    b.Property<int>("KnowledgeCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("knowledge_cost");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("Quote")
                        .HasColumnType("text")
                        .HasColumnName("quote");

                    b.Property<string>("ServiceClasses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("service_classes");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TimeLimitSec")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_sec");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_questions_source_id");

                    b.HasIndex("Type", "Status")
                        .HasDatabaseName("ix_questions_type_status");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.ScaleRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("FailureThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("failure_threshold");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("mandatory");

                    b.Property<int>("Max")
                        .HasColumnType("integer")
                        .HasColumnName("max");

                    b.Property<int>("Min")
                        .HasColumnType("integer")
                        .HasColumnName("min");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Start")
                        .HasColumnType("integer")
                        .HasColumnName("start");

                    b.HasKey("Code")
                        .HasName("pk_scales");

                    b.ToTable("scales", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.ServiceClassRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Code")
                        .HasName("pk_service_classes");

                    b.ToTable("service_classes", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.SourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.SwipeAnswerRecord", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_ms");

                    b.Property<bool>("IsRepeat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_repeat");

                    b.Property<int>("KnowledgeDelta")
                        .HasColumnType("integer")
                        .HasColumnName("knowledge_delta");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("question_snapshot");

                    b.Property<string>("ScaleChanges")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scale_changes");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verdict");

                    b.HasKey("ShiftId", "Seq")
                        .HasName("pk_swipe_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_swipe_answers_question_id");

                    b.ToTable("swipe_answers", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.SwipeShiftRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CardShownAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("card_shown_at");

                    b.Property<int?>("Cycle")
                        .HasColumnType("integer")
                        .HasColumnName("cycle");

                    b.Property<string>("Deck")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("deck");

                    b.Property<string>("FailureScale")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_scale");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<Guid?>("PreviousCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_cycle_id");

                    b.Property<string>("Scales")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scales");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_swipe_shifts");

                    b.HasIndex("PreviousCycleId")
                        .HasDatabaseName("ix_swipe_shifts_previous_cycle_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_swipe_shifts_user_id");

                    b.ToTable("swipe_shifts", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.TripJournalRecord", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("CriticalError")
                        .HasColumnType("boolean")
                        .HasColumnName("critical_error");

                    b.Property<int?>("ElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_ms");

                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_id");

                    b.Property<int?>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("FlagsSet")
                        .HasColumnType("jsonb")
                        .HasColumnName("flags_set");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int>("KnowledgeDelta")
                        .HasColumnType("integer")
                        .HasColumnName("knowledge_delta");

                    b.Property<string>("OptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("option_id");

                    b.Property<string>("OutcomeStepId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("outcome_step_id");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<string>("ScaleChanges")
                        .HasColumnType("jsonb")
                        .HasColumnName("scale_changes");

                    b.Property<string>("StepId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("step_id");

                    b.Property<bool>("TimedOut")
                        .HasColumnType("boolean")
                        .HasColumnName("timed_out");

                    b.Property<string>("ToStepId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_step_id");

                    b.Property<string>("VariantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("variant_id");

                    b.Property<bool>("VoiceApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("voice_applied");

                    b.Property<string>("VoiceAttemptId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voice_attempt_id");

                    b.Property<string>("VoiceChoice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voice_choice");

                    b.Property<double?>("VoiceConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("voice_confidence");

                    b.Property<string>("VoiceError")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("voice_error");

                    b.Property<int?>("VoiceLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("voice_latency_ms");

                    b.Property<int?>("VoiceLayaLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("voice_laya_latency_ms");

                    b.Property<int?>("VoiceLlmLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("voice_llm_latency_ms");

                    b.Property<string>("VoicePassengerReply")
                        .HasColumnType("text")
                        .HasColumnName("voice_passenger_reply");

                    b.Property<string>("VoiceReplyError")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("voice_reply_error");

                    b.Property<DateTimeOffset?>("VoiceReplyStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voice_reply_started_at");

                    b.Property<string>("VoiceRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("voice_request_id");

                    b.Property<string>("VoiceRoleStages")
                        .HasColumnType("jsonb")
                        .HasColumnName("voice_role_stages");

                    b.Property<double?>("VoiceSafetyConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("voice_safety_confidence");

                    b.Property<double?>("VoiceSafetyViolation")
                        .HasColumnType("double precision")
                        .HasColumnName("voice_safety_violation");

                    b.Property<double?>("VoiceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("voice_score");

                    b.Property<double?>("VoiceScoreConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("voice_score_confidence");

                    b.Property<int?>("VoiceSttLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("voice_stt_latency_ms");

                    b.Property<string>("VoiceTranscript")
                        .HasColumnType("text")
                        .HasColumnName("voice_transcript");

                    b.HasKey("TripId", "Seq")
                        .HasName("pk_trip_journal");

                    b.HasIndex("TripId", "VoiceAttemptId")
                        .IsUnique()
                        .HasDatabaseName("ix_trip_journal_trip_id_voice_attempt_id")
                        .HasFilter("\"kind\" = 'voiceAttempt'");

                    b.ToTable("trip_journal", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.TripRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("directory");

                    b.Property<string>("EventVersions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_versions");

                    b.Property<string>("FailureCause")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("failure_cause");

                    b.Property<string>("FailureScale")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_scale");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("ServiceClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_class");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("StepStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("step_started_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trips_user_id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.TripSettingsRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.HasKey("Id")
                        .HasName("pk_trip_settings");

                    b.ToTable("trip_settings", (string)null);
                });

            modelBuilder.Entity("TurboSquadApp.Data.AppUser", b =>
                {
                    b.HasOne("TurboSquadApp.Data.Brigade", "Brigade")
                        .WithMany()
                        .HasForeignKey("BrigadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_brigades_brigade_id");

                    b.HasOne("TurboSquadApp.Data.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_depots_depot_id");

                    b.Navigation("Brigade");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("TurboSquadApp.Data.AppUserRole", b =>
                {
                    b.HasOne("TurboSquadApp.Data.AppUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurboSquadApp.Data.BlitzAnswerRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.BlitzSessionRecord", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blitz_answers_blitz_sessions_session_id");
                });

            modelBuilder.Entity("TurboSquadApp.Data.BlitzSessionRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blitz_sessions_users_user_id");
                });

            modelBuilder.Entity("TurboSquadApp.Data.Brigade", b =>
                {
                    b.HasOne("TurboSquadApp.Data.Depot", "Depot")
                        .WithMany("Brigades")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brigades_depots_depot_id");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("TurboSquadApp.Data.ConductorProfileRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conductor_profiles_users_user_id");
                });

            modelBuilder.Entity("TurboSquadApp.Data.EventDraftRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.SourceRecord", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_event_drafts_sources_source_id");
                });

            modelBuilder.Entity("TurboSquadApp.Data.KnowledgeMasteryRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_masteries_users_user_id");
                });

            modelBuilder.Entity("TurboSquadApp.Data.QuestionRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.SourceRecord", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_questions_sources_source_id");

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("TurboSquadApp.Data.SwipeAnswerRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.QuestionRecord", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_swipe_answers_questions_question_id");

                    b.HasOne("TurboSquadApp.Data.SwipeShiftRecord", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_swipe_answers_swipe_shifts_shift_id");
                });

            modelBuilder.Entity("TurboSquadApp.Data.SwipeShiftRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.SwipeShiftRecord", null)
                        .WithMany()
                        .HasForeignKey("PreviousCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_swipe_shifts_swipe_shifts_previous_cycle_id");

                    b.HasOne("TurboSquadApp.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_swipe_shifts_users_user_id");
                });

            modelBuilder.Entity("TurboSquadApp.Data.TripJournalRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.TripRecord", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_journal_trips_trip_id");
                });

            modelBuilder.Entity("TurboSquadApp.Data.TripRecord", b =>
                {
                    b.HasOne("TurboSquadApp.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_users_user_id");
                });

            modelBuilder.Entity("TurboSquadApp.Data.AppUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TurboSquadApp.Data.Depot", b =>
                {
                    b.Navigation("Brigades");
                });
#pragma warning restore 612, 618
        }
    }
}
